CONFIG = {'dev': '/dev/usb-ir-lesekopf0',
          'loglevel': 'ERROR',
          'utc': True,
          'mqtt': {'enabled': True,
                   'host': 'localhost',
                   'port': 1883,
                   'keepalive': 60,
                   'auth': {'enabled': True, 'username': 'mqtt_user', 'password': 'pwd' },
                   'topic': 'devices/powermeter/reading',
                   'retain': False,
                   'qos': 0 } ,
          'logfile': {'enabled': False},
          'sqlite': {'enabled': True,
                     'fname': '/mnt/usb-stick/meterdata/powermeter_%Y-%m.sqlite3',
                     'min_rows_insert': 5},
         } 
